### ISSUE TITLE
Cannot copy image to clipboard

### ISSUE THREAD

**Issue by txj-xyz** [pvme/preset-maker#32]
I am attempting to use the following saved preset to get the image from it.

https://pvme.github.io/preset-maker/#/6ggokHvtrlrEtOeIFaOJ

Here is a video of it not working

https://cdn.txj.sh/aefLf

**Comment by txj-xyz** [comment]
Firefox

**Comment by txj-xyz** [comment]
https://user-images.githubusercontent.com/7461476/234931267-f2c8fd51-a06f-40c3-9fb7-fd512f21c9fe.mp4

**Comment by nullopt** [comment]
Resolved in #35
